title: Alexander O. Smith
description: "PhD Student, iSchool, Syracuse University"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alexanderosmith.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Alexander O. Smith
author-image:   aos_bw.png
author-job:     PhD Student, iSchool, Syracuse University
author-email:   aosmith@syr.edu # Add your email for contant form.
author-twitter: alexander0wen # Add your twitter account
about-author:  I am a PhD student of memes, the study of dreams.

# Social settings
social-twitter:   alexander0wen
social-facebook:  aos11409
social-github:    alexanderosmith
#social-pinterest: name
social-instagram: alexander__owen
#social-youtube:
#social-vk:
social-linkedin: aos11409

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-113001384-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: https-aos11409-github-io # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE
  - README.md
